//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Take_Leaves
    {
        public int id { get; set; }
        public string emp_code { get; set; }
        public int leave_id { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public int no_of_days { get; set; }
        public int financial_year_start { get; set; }
        public int financial_year_end { get; set; }
        public int absent_days { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leave { get; set; }
    }
}
