//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Other_Leave_Counts
    {
        public string code { get; set; }
        public int maternity_leave_count_left { get; set; }
        public int paternity_leave_count_left { get; set; }
        public int child_adoption_leave_count_left { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
