//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees_Take_Leaves = new HashSet<Employees_Take_Leaves>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string post { get; set; }
        public string type_of_institute { get; set; }
        public string posting_place { get; set; }
        public string block_hq { get; set; }
        public string gender { get; set; }
    
        public virtual Employees_Other_Leave_Counts Employees_Other_Leave_Counts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Take_Leaves> Employees_Take_Leaves { get; set; }
    }
}
